#!/bin/bash
# Generate a source file that can be passed through yosys using the atf15xx_yosys scripts from a Quartus 13 .qsf file
# Usage: convert.sh <project-name.qsf>

if [ "$#" -ne 1 ]; then
    echo "Usage: convert.sh <project-name.qsf>"
    exit 1
fi

echo "// -----------------------------------------------------"
echo "// Generated by convert.sh from $1"
echo "// Don't edit this file, edit the project files instead "
echo "// -----------------------------------------------------"

# Write include statements for any sub files
echo ""
sed -n -e '/VERILOG_FILE/ s/.* \([^ ]*\)$/\1/p' "$1" | while read -r file; do
    cat "${file//\"/}"
done
echo ""
echo ""

# Write out the top level verilog file
# cat "$(basename "$1" .qsf).v"

echo ""
echo ""
echo "// -----------------------------------------------------"
echo "// Chip and pin assignments"
echo "// -----------------------------------------------------"

# Put a line to define the chip type
echo -n "//PIN: CHIP \"$(basename "$1" .qsf)\" ASSIGNED TO A "
sed -n -e '/DEVICE_FILTER_PACKAGE/ s/.* \([^ ]*\)$/\1/p' "$1" | tr -d '\n'
sed -n -e '/DEVICE_FILTER_PIN_COUNT/ s/.* \([^ ]*\)$/\1/p' "$1"

# Print out the pin mappings
sed -n -e '/^set_location_assignment / s/ -to//;s/set_location_assignment PIN_/\/\/PIN: /p;s/\([^ ]*\) *\([^ ]*\) *\([^ ]*\)/\1 \3 \2/' "$1"
